### ISSUE TITLE
Socat support

### ISSUE THREAD

**Issue by thatnerdjosh** [JorisE/yapfify.el#15]
@proofit404 would it be reasonable to add socat support to this like in https://github.com/proofit404/anaconda-mode?

If so, I don't mind diving in and trying to implement this, would be a cool project for me

**Comment by proofit404** [comment]
Hi,

`socat` in anaconda-mode is used to open port from inside docker container. Yapf is running over tramp without network operations. Only stdin, stdout are used.

But you can try to work on #13 to earn similar experience.

Regards, Artem.
