### ISSUE TITLE
[feature request] A configuration option to set an absolute path to the yapf executable

### ISSUE THREAD

**Issue by SergiyKolesnikov** [JorisE/yapfify.el#18]
It would be nice to have a configuration option to set an absolute path to the yapf executable, so it does not have to be on the `PATH`. This feature would be useful when yapf is installed in Anaconda for example. Since version 4.4 Anaconda explicitly recommends not to put its `bin` directory on `PATH`, which makes the yapf executable unavailable for yapfify if none of the Anacondas virtual environments is activated.

**Comment by gariepyalex** [comment]
Fixed in https://github.com/JorisE/yapfify/pull/23
