### ISSUE TITLE
void-function mapcar*

### ISSUE THREAD

**Issue by jangid** [JorisE/yapfify.el#22]
I am getting this error on emacs-27 branch.

```
Debugger entered--Lisp error: (void-function mapcar*)
  mapcar*(set-window-start (#<window 3 on hello.py>) (1))
  yapfify-region(1 2941)
  yapfify-buffer()
  run-hooks(before-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

**Comment by JorisE** [comment]
I am at emacs 27.0.50 but don't have that error. What exact version are you using? I don't think mapcar* has been deprecated.

What happens if you search for `mapcar*` using `C-h f`?

**Comment by neoeleatic** [comment]
I'm at emacs 26.3 and I also have this error. yapfify worked until I updated a bunch of unrelated(?) packages. Then this error appeared. When I add this (verbatim from [https://www.gnu.org/software/emacs/manual/html_node/elisp/Mapping-Functions.html#Mapping-Functions](url)) to yapfify.el, the error is gone:

```lisp
(defun mapcar* (function &rest args)
            "Apply FUNCTION to successive cars of all ARGS.
          Return the list of results."
            ;; If no list is exhausted,
            (if (not (memq nil args))
                ;; apply function to cars.
                (cons (apply function (mapcar 'car args))
                      (apply 'mapcar* function
                             ;; Recurse for rest of elements.
                             (mapcar 'cdr args)))))
```

In my emacs C-h f only finds mapcar.  I don't think mapcar* is part of my emacs distribution. It came from somewhere else. No idea from where, though.

**Comment by JorisE** [comment]
`mapcar*` no longer exists in cl-lib. I hope this was fixed in https://github.com/JorisE/yapfify/commit/0b4f20af0b00a86353ddc286df26eade89381269
