### ISSUE TITLE
[Feature request] Yapfify-region?

### ISSUE THREAD

**Issue by dieggsy** [JorisE/yapfify.el#3]
It would be nice if there was a yapfify region command, or one that would act on the current region if a region is selected, but the whole buffer if no region is selected. This would give a little more fine-tuned control over what gets formatted when.

**Comment by JorisE** [comment]
Thanks for the FR!

If I find the time I might look into this, but I have never felt the need for it. A PR would definitely be considered.

**Comment by JorisE** [comment]
Fixed in #5!
