### ISSUE TITLE
Make yapf errors less annoing.

### ISSUE THREAD

**Issue by proofit404** [JorisE/yapfify.el#4]
When programming furiously I frequently save buffer with incorrect python code. Each time `*Yapf errors*` buffer pops up. I guess message in the echo area will be sophisticated. What do you think?

**Comment by JorisE** [comment]
I agree. I was using rust-mode recently and noticed it does what you are [describing](https://github.com/rust-lang/rust-mode/blob/master/rust-mode.el#L1282), it is much more convenient.

**Comment by JorisE** [comment]
I think this was fixed in f8b1406aef5f61ebaa841cde09f66d06dfb63bd4

**Comment by proofit404** [comment]
Thanks for quick fix!

**Comment by neverfox** [comment]
So when I'm working on a Python project, I'm left with 50-60 yapfify buffers hanging around. Is that normal? Is there something I should change about my workflow to prevent this or is there a garbage collection that could happen here?

**Comment by proofit404** [comment]
Most of the time they have SyntaxError message, so they can be deleted safely. There is no garbage collection of such buffers yet.

**Comment by JorisE** [comment]
I noticed that. We should probably fix that :) https://github.com/JorisE/yapfify/issues/14
