### ISSUE TITLE
Yapf mode lose point position after buffer save.

### ISSUE THREAD

**Issue by proofit404** [JorisE/yapfify.el#8]
With yapf-mode enabled point goes somewhere into buffer beginning on each save call.

If you call `yapfify-buffer` interactively this doesn't happen.

**Comment by JorisE** [comment]
I'm not observing that behaviour. Do you have an example file?

**Comment by proofit404** [comment]
It happens to all files. I start observing this behavior after 0.0.5 release. I can write screen cast if it helps.

Maybe it depends on Emacs version.
```
GNU Emacs 26.0.50 (build 16, x86_64-pc-linux-gnu, GTK+ Version 2.24.31) of 2017-05-09
```

**Comment by toshism** [comment]
I can't recreate this either.
I'm running

> GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-03-29, modified by Debian

**Comment by proofit404** [comment]
This error was triggered by my side project isortify, which creation was inspired by this library.

Fixed in this commit https://github.com/proofit404/isortify/commit/2db50c1f585db8a8ec5fa28a90a8179516c16cd0

**Comment by JorisE** [comment]
👍
