### ISSUE TITLE
Can't yapf with vimish folding

### ISSUE THREAD

**Issue by ntcong** [JorisE/yapfify.el#9]
I'm using vimish-fold to improve folding. Whenever I create a fold, yapf refuse to run and only output:
`copy-to-buffer: Text is read-only`

**Comment by toshism** [comment]
This is due to vimish fold setting "folded" text to read only. Yapfify replaces the entire buffer with the response from yapf. If you try it with everything unfolded, I suspect it will work.

**Comment by JorisE** [comment]
Because this is not really an issue I think we can solve, I will close this.
